#logging:
#  pattern:
##  定制输出格式
#    console: "%d - %msg%n"
##  日志输出级别
#  level: info
##  日志输出文件目录
#  file: /Users/hommin/Documents/document/my-log/sell.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.120/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell

imooc:
  sell:
    address: http://hommin-sell.natapp1.cc/sell/
    wechat:
      appid: wx48458d7156023188
      appsecret: 3aca041bf480ca1325e7bf3ce14afe89
      mchId: 148xxxxxxxx
      mchKey: xxxxxxxxx
      keyPath: /var/weixin_cert/h5.p12
      notifyUrl: http://hommin-sell.natapp1.cc/sell/pay/notify